"""Initial migration.

Revision ID: 7a83a3ea761d
Revises: 
Create Date: 2024-05-30 02:29:03.627269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a83a3ea761d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_summary', schema=None) as batch_op:
        batch_op.alter_column('summaryDate',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['userEmail'])
        batch_op.create_unique_constraint(None, ['userName'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tbl_summary', schema=None) as batch_op:
        batch_op.alter_column('summaryDate',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###
