"""Add kg_data and entities columns to tbl_summary

Revision ID: e8fba73e5006
Revises: 7a83a3ea761d
Create Date: 2024-06-25 23:04:11.167916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fba73e5006'
down_revision = '7a83a3ea761d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kg_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_summary', schema=None) as batch_op:
        batch_op.drop_column('entities')
        batch_op.drop_column('kg_data')

    # ### end Alembic commands ###
